version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: nitro_postgres_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nitro_development
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nitro_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U nitro_development -d nitro_development"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
